spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_order_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: coffeemanager
    password: password

  thymeleaf:
    cache: false

